version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sailsjs-skeleton
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /srv/data/mysql:/var/lib/mysql
    command: mysqld --sql_mode=""

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80

  mongo:
    image: mongo:xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  redis:
    image: redis:3

  redis-commander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    depends_on:
      - redis
    ports:
      - 8079:8081

  app:
    hostname: docker-sailsjs-skeleton
    build:
      context: etc/docker/dev/app
    depends_on:
      - mysql
      - mongo
      - redis
    ports:
      - 80:1337
    volumes:
      - .:/app
    tty: true
    environment:
      MYSQL_DATABASE: sailsjs-skeleton
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MONGO_DATABASE: sailsjs-skeleton
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
